### ISSUE TITLE
Refactor TravisCI configuration

### ISSUE THREAD

**Issue by Zerg1996** [NilFoundation/multiprecision#17]
In travis.yml all the Boost libraries get installed for each test case. This is redundant and requires to be refactored: install Boost.Multiprecision-required libraries only.

**Comment by Zerg1996** [comment]
Done with 45dee3c

**Comment by nemothenoone** [comment]
@Zerg1996 AppVeyor integration task could be moved to https://github.com/NilFoundation/multiprecision/issues/22
